[package]
name = "aoc-2016"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
md-5 = "0.9"
num = "0.4"
regex = "1"
